### PR TITLE
Fix break in #67. Follow-up for #69.

### PR DESCRIPTION
**Pull request by unakatsuo**
Renamed the branch name without ``#``. Old name caused the build error.

Original Change: #69

### CODE REVIEW

**Comment by unakatsuo** [comment]
Got same build error again...

https://ci.openvdc.org/job/citest/job/fix-PR67/1/console

```
+ docker build -t unit-tests.citest.fix-PR67.el7 -f ./deployment/docker/el7-unit-tests.Dockerfile .
invalid value "unit-tests.citest.fix-PR67.el7" for flag -t: Error parsing reference: "unit-tests.citest.fix-PR67.el7" is not a valid repository/tag
See '/usr/bin/docker-current build --help'.
+ docker_rm
```

**Comment by unakatsuo** [comment]
Docker 1.10 seems to be changed to reject uppercase tag name.

https://github.com/docker/docker/issues/20056

Our docker host stats:

```
$ rpm -qa | grep docker
docker-selinux-1.10.3-46.el7.centos.14.x86_64
docker-1.10.3-46.el7.centos.14.x86_64
docker-common-1.10.3-46.el7.centos.14.x86_64
$ uname -a
Linux localhost.localdomain 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Metallion** [comment]
Oh, so basically all our branch names need to be lowercase only? Or we could have a script downcase them.

**Comment by Metallion** [comment]
Will merge once the CI passes. :)

**Pull request merged**
