### PR TITLE
Fix lxc test

### PR DESCRIPTION
**Pull request by b0r6**
Fixed the test.

### CODE REVIEW

**Comment by Metallion** [comment]
Getting this error:

```
[vagrant@openvdc-1box lxc]$ go test
INFO[0000] Registered hypervisor provider: lxc

INFO[0000] Creating lxc-container...                     hypervisor=lxc
lxc_container: utils.c: get_template_path: 1128 No such file or directory - bad template: download
lxc_container: lxccontainer.c: lxcapi_create: 1223 bad template: download
```

It seems to be looking for a nonexistant template called `download`.

**Comment by b0r6** [comment]
The "bad template: download"-error seems to happen if "lxc-templates" isn't installed.

**Comment by Metallion** [comment]
Note to self:

Steps required to make this test work:

```
sudo yum install lxc lxc-templates bridge-utils
sudo brctl addbr virbr0
```

Looks like the network settings are currently dependent on DHCP. Gonna fix it to use static networking instead.

**Comment by Metallion** [comment]
Actually after more considering and discussion, we've decided to skip this test. A test that involves an actual container being started should be done at the integration test level and not unit test level.

**Pull request merged**
