### PR TITLE
Handle multiple instance states after first boot.

### PR DESCRIPTION
**Pull request by unakatsuo**
Allow operation to bring instance state:
* ``RUNNING`` -> ``TERMINATED``
* ``RUNNING`` -> ``STOPPED``
* ``STOPPED`` -> ``RUNNING``

- [x] Save mesos slave ID to Instance model.
- [x] Make ``openvdc destroy i-xxxx`` work.
- [x] Make ``openvdc stop i-xxxx`` work.
- [x] Make ``openvdc start i-xxxx`` work.
- [x] ``openvdc show`` shows instance details.
- [x] API Server builds Executor ID from Instance model.

### CODE REVIEW

**Comment by unakatsuo** [comment]
Confirmed that the added features have worked on my laptop. 

```
UnaBookPro:openvdc unakatsuo$ ./openvdc run centos/7/null
INFO[0001] Found template: centos/7/null                
instance_id:"i-0000000011" resource_id:"r-0000000009" 
UnaBookPro:openvdc unakatsuo$ ./openvdc show i-0000000011
ID: "i-0000000011"
instance: <
  id: "i-0000000011"
  slave_id: "27556c25-8388-40e3-94e3-fbbf6b57eff9-S0"
  resource_id: "r-0000000009"
  last_state: <
    state: RUNNING
    created_at: <
      seconds: 1481089206
      nanos: 672754333
    >
  >
>
UnaBookPro:openvdc unakatsuo$ ./openvdc show r-0000000009
ID: "r-0000000009"
resource: <
  id: "r-0000000009"
  type: RESOURCE_NULL
  null: <
  >
  template_uri: "https://raw.githubusercontent.com/axsh/openvdc/generalize-template/centos/7/null.json"
>
UnaBookPro:openvdc unakatsuo$ ./openvdc stop i-0000000011
instance_id:"i-0000000011" 
UnaBookPro:openvdc unakatsuo$ ./openvdc show i-0000000011
ID: "i-0000000011"
instance: <
  id: "i-0000000011"
  slave_id: "27556c25-8388-40e3-94e3-fbbf6b57eff9-S0"
  resource_id: "r-0000000009"
  last_state: <
    state: STOPPED
    created_at: <
      seconds: 1481089260
      nanos: 515040158
    >
  >
>
UnaBookPro:openvdc unakatsuo$ ./openvdc start i-0000000011
instance_id:"i-0000000011" 
UnaBookPro:openvdc unakatsuo$ ./openvdc show i-0000000011
ID: "i-0000000011"
instance: <
  id: "i-0000000011"
  slave_id: "27556c25-8388-40e3-94e3-fbbf6b57eff9-S0"
  resource_id: "r-0000000009"
  last_state: <
    state: RUNNING
    created_at: <
      seconds: 1481089272
      nanos: 589763245
    >
  >
>
UnaBookPro:openvdc unakatsuo$ ./openvdc destroy i-0000000011
instance_id:"i-0000000011" 
UnaBookPro:openvdc unakatsuo$ ./openvdc show i-0000000011
ID: "i-0000000011"
instance: <
  id: "i-0000000011"
  slave_id: "27556c25-8388-40e3-94e3-fbbf6b57eff9-S0"
  resource_id: "r-0000000009"
  last_state: <
    state: TERMINATED
    created_at: <
      seconds: 1481089280
      nanos: 753397490
    >
  >
>
```

**Comment by unakatsuo** [comment]
A few more unmerged commits to master.

**Comment by b0r6** [comment]
:+1: Works for me as well.

**Comment by Metallion** [comment]
Thanks for the review. :)

**Pull request merged**
